### ISSUE TITLE
WorkflowError("For PEP support, please install peppy.") when running workflow

### ISSUE THREAD

**Issue by lenakinzel** [IKIM-Essen/uncovar#325]
Problem occurs with python version 3.10.0 -> manually downgrading to python version 3.9.7 fixes the problem for now

**Comment by thomasbtf** [comment]
The following PR should fix this issue. https://github.com/conda-forge/peppy-feedstock/pull/8

**Comment by nsheff** [comment]
This will also be fixed with peppy version 0.32.0, which will be released soon.

**Comment by thomasbtf** [comment]
Conda-forge implemented a patch, over at https://github.com/conda-forge/peppy-feedstock/pull/9. 
This patch is live since yesterday (see https://anaconda.org/conda-forge/peppy).

@lenakinzel Could you please try out the deployment method described in the [snakemake workflow catalogue](https://snakemake.github.io/snakemake-workflow-catalog/?usage=IKIM-Essen%2Funcovar) again and see, if its works now? :)

**Comment by thomasbtf** [comment]
We have to wait for another patch: https://github.com/conda-forge/peppy-feedstock/pull/10
